# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only
params:
  modes: 12
  width: 32
  s: 40
name: geofno3lay
size: 1500000
iphi_lr: 0.0001
