# @package _global_
# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only

model:
  params:
    dim_h: 32
    message_passing_steps: 13
  name: gen_nograph
  size: 5000
