# @package _global_
# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only
dataset:
  type: navierstokes
  path: data/navierstokes
experiment:
  batch_size: 128
  nb_epochs: 100
  freq: 100
model:
  params:
    dim_x: 2
    dim_yc: 1
    dim_yt: 1
