# @package _global_
# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only
dataset:
  type: sin
  f: 0.1
  n_x: 64
experiment:
  batch_size: 128
  nb_epochs: 2000
  freq: 2000
model:
  params:
    dim_x: 2
    dim_yc: 1
    dim_yt: 1
hydra:
  run:
    dir: outputs/${name}/${dataset.type}-f${dataset.f}/${now:%H-%M-%S}
  job:
    chdir: True
