# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only
params:
  dim_h: 32
  nhead: 2
  nlayers_encoder: 2
  nlayers_decoder: 4
name: tfsnormalfour
size: 20000
