# Copyright © <2023> Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Arnaud Pannatier <arnaud.pannatier@idiap.ch>
#
# SPDX-License-Identifier: LGPL-3.0-only
params:
  dim_h: 32
  nhead: 2
  nlayers: 4
  share_blocks: True
name: encoder_only
size: 5000
